- src/home/home-product-hero.tsx
Taken from @cairomassimo's commit db333e0e93fbea8ffe7af953105bb25a570c0a49
Committing it again here so it can be signed
> 🌲 Fix home background clipped on very wide screens - Verified

- src/ce/ce-showcase.tsx
Quick copy change to the community edition page!
> Refer to the community edition as the Tally Wallet

- src/common/footer.tsx
- src/layout/legal-layout.tsx
- src/pages/ccpa.mdx
- src/pages/privacy.mdx
> Improve layout of privacy and CCPA pages

- src/common/nav.tsx
Closes #42. Opens https://boards.greenhouse.io/tallywallet/ in a new tab.
> Add "Jobs" footer link

- src/features/Home/PolygonBanner/index.tsx
> 💥 Change banner copy to Optimism coming soon

- src/features/Home/PolygonBanner/index.tsx
> 🦋 Add "Arbitrum" to banner

- src/features/Footer/Nav/index.tsx
- src/features/Header/index.tsx
- src/features/Home/Hero/index.tsx
Updated links for ad campaign, Signed this time!
> add links directly to chrome store and sign commit

- manifesto-dapp-backend/functions/src/index.ts
- src/features/Manifesto/ManifestoPanel/ManifestoPanelSigned/ClaimDiscordRole.tsx
Closes Petition - One signature can promote N discord usernames. #83
Closes #83
> implement 1 address 1 discord role restriction

- manifesto-dapp-backend/functions/src/index.ts
into the success path of the actual role
assignment call
> move discord role persist

- src/features/Home/index.tsx
This reverts commit 5c0a3998e9435e96a2597b8e65ca67a9dd6594d2.
> Show community pledge on home page

- src/features/Home/Features/index.tsx
- src/features/Home/PolygonBanner/index.tsx
Changes from this ticket
Closes https://github.com/tallycash/tally.cash/issues/106
> Optimism update

- src/features/Home/Features/index.tsx
- src/features/Home/PolygonBanner/index.tsx
- src/features/Home/index.tsx
Closes tallycash/extension#2454
This PR makes Arbitrum website updates
**UI**
**Before**
**After**
> Arbitrum website updates

- src/features/Header/index.tsx
- src/features/Home/Features/index.tsx
- src/features/Subscribe/index.tsx
- Removed "Security" and "DAO" from header links (looks cleaner and having DAO in the header makes it sound like we are a DAO already) + dded "Web3 Pledge" to make the page more visible.
- Edited newsletter signup copy
- Other minor copy polish for clarity, grammar, and pith.
> ✏️ Update copy and site header

- src/features/Footer/Nav/index.tsx
Changed Twitter link in footer
> Update index.tsx 

- static/snapshot-strategies/dummy.json
adding a dummy json to test the snapshot
> adding dummy json file

- src/features/Home/PolygonBanner/index.tsx
- src/features/Home/index.tsx
- src/pages/ccpa.mdx
- src/pages/privacy.mdx
Reverts tallyhowallet/tallyho.org#136 per request from @mr-michael ; we weren't quite ready to go here.
> Revert "Removed CCPA page. Fixes #134"

- src/features/Home/Features/index.tsx
Resolves https://github.com/tahowallet/taho.xyz/issues/173
Updated section:
> Update "Coming soon" section

- src/features/Home/PolygonBanner/index.tsx
> Update waitlist banner

- src/pages/goodbye.tsx
- src/shared/hooks/index.ts
Resolves #170 
What has been done:
- Fixed the height issue
- Added `useFullHeight` hook
> Fix background height on Goodbye page

- src/features/Header/index.tsx
Let's take out the Roadmap from the header.
> Remove `/roadmap` from nav
